# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Superscript Linux

on:
  release:
    types: [published, created, edited]

jobs:
  generate:
    name: Build Linux
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install Dependencies
        run: pip install -r requirements.txt
        working-directory: src/
      - name: Give Execute Permission
        run: chmod +x build-CLI.sh
        working-directory: build/
      - name: Build Binary
        run: ./build-CLI.sh5
        working-directory: build/