# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Superscript Unit Tests

on:
  release:
    types: [published, edited]

jobs:
  generate:
    name: Build Linux
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout master
      uses: actions/checkout@master
